org: joaogoncalves
app: events-api
service: events-api
frameworkVersion: "3"

custom: ${file(./resources/custom.yml)}

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline # used for local execution
  - serverless-esbuild # used for compiling/packaging the Typescript code
  - serverless-dynamodb

package:
  individually: true

provider: ${file(./resources/provider.yml)}

functions: ${file(./resources/functions.yml)}

resources: ${file(./resources/resources.yml)}
