name: Deploy dev

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-dev:
    name: deploy-dev
    runs-on: ubuntu-latest
    environment: dev

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy -s $STAGE
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

  deploy-staging:
    name: deploy-staging
    runs-on: ubuntu-latest
    environment: staging
    needs: deploy-dev

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy -s $STAGE
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
