name: Merge master branch to staging
on:
  push:
    branches:
      - master
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: staging
          message: Merge master into staging
          github_token: ${{ secrets.GITHUB_TOKEN }}
