name: Merge staging branch to prod
on:
  workflow_dispatch:
    branches:
      - staging

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging -> prod
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: staging
          message: Merge staging into prod
          github_token: ${{ secrets.GITHUB_TOKEN }}
